### ISSUE TITLE
enhance packager

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#106]
- [x] Add xx-XX.finder_cli.ini which does not follow "normal" file names.
- [ ]  Allow creation/editing of the xx-XX.localise.php, by adding it to the view and letting copy from reference in a codemirror editable instance.
- [ ] Allow creation/editing of the xx-XX.css, by adding it to the view in a codemirror editable instance.
- [ ] Allow, when making a core pack, adding some stuff in the media folder (calendar for Farsi is a good exemple)

**Comment by javigomez** [comment]
see related pull at #105

**Comment by infograf768** [comment]
finder_cli.ini done
see https://github.com/joomla-projects/com_localise/pull/113

**Comment by infograf768** [comment]
This has been done except editing the css itself, but it can be added. Closing
