### ISSUE TITLE
Error While trying to delete a Language

### ISSUE THREAD

**Issue by puneet0191** [joomla-projects/com_localise#120]
When We try to Delete a Language, We are getting an error messages like this

![image](https://cloud.githubusercontent.com/assets/3048593/3329094/8887bc88-f7c3-11e3-8446-6967b77ffff9.png)

**Comment by javigomez** [comment]
thanks for the report

**Comment by infograf768** [comment]
Solved by the commit above https://github.com/joomla-projects/com_localise/commit/cff2def939fa518601cdf53948757017f84797ac
