### ISSUE TITLE
move JFormField to JFormFieldList? 

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#127]
https://github.com/joomla-projects/com_localise/pull/125/files#discussion_r14049381

**Comment by infograf768** [comment]
I have added a PR which also deals with other fields. Please test https://github.com/joomla-projects/com_localise/issues/224

**Comment by Ayeko** [comment]
He JM
test

**Comment by infograf768** [comment]
@Ayeko
If you have tested the PR, please comment OK on the PR itself

**Comment by Skullbock** [comment]
I think this one can be closed @javigomez
