### ISSUE TITLE
export in package list allow to export not valid packages

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#129]
@infograf768 I just tested this export button with an empty package and it allows to download unfinished packages, please check:
http://www.youtube.com/watch?v=Eer8zVBqMyE

What are the plans for this defaults packages that are generated on install. Should we add title and the rest of the data by default?

**Comment by infograf768** [comment]
Export is broken.
My guess is that its function was initially to make the .zip (what our Download now does)

What we could do is to use it to Export the package_name.xml which is in com_localise/packages/
That xml could then be used on another site if we create an "Import" button that will browse and let save into com_localise/packages/

**Comment by infograf768** [comment]
Also, we may want to create another section fo the component to deal with github and using its own Export and Import function

**Comment by infograf768** [comment]
Implemented Export and Import package xml in PRs
See 
https://github.com/joomla-projects/com_localise/pull/163
https://github.com/joomla-projects/com_localise/pull/161
