### ISSUE TITLE
remove old comment line checks

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#132]
@infograf768, do you agree that we can remove this feature that parses commented lines: https://github.com/joomla-projects/com_localise/blob/develop/component/admin/helper.php#L67-L70

We are not goign to use this SVN headers anymore isn't it?

**Comment by infograf768** [comment]
Some Translation Teams are using SVN in collaboration and I have seen some errors where the ini had still these #.
I suggest to leave the code in case of as it does not cost much and corrects the issue when the file is saved by com_localise

**Comment by javigomez** [comment]
I was checking this helper and I think that we are just not using it anywhere in the component. I'm going to do some more testing and I think I will remove it. Probably was a feature from the past

**Comment by infograf768** [comment]
I think we do use it. It takes care of these # and of the BOM value if wrong. It lets know which reference string has changed, is extra, etc. It is a very important file for com_localise

**Comment by infograf768** [comment]
Hmm, looks like all this code is now in the translation model
