### ISSUE TITLE
Can't see languages or translations

### ISSUE THREAD

**Issue by Achal-Aggarwal** [joomla-projects/com_localise#162]
If language filter is selecting a language and you delete it then the filter will show " - Select language - " options as selected but the view doesn't show any language.

Steps to reproduce:
1. Create a dummy language.
2. Using filter change view to only display newly created dummy lang.
3. delete that language. (by clicking on red (X))
4. Now check filters.
5. Try changing view to "Translation", still no data on the view.

**Comment by infograf768** [comment]
It is normal to not see any translations when the language xml for that client is deleted, as deleting that xml also deletes the xx-XX folder in the client language/ folder.

As long as you have one xml for the language (whatever the client, i.e. whether it exists in Site, Installation, or Administrator), the language name will appear in the Select Language

**Comment by Achal-Aggarwal** [comment]
I think you misunderstood me, take a look at https://www.youtube.com/watch?v=OrIFXt20dD8

**Comment by infograf768** [comment]
Understand. This happens when we have only one client xml for the language and one deletes it. It is solved by choosing a client or changing the language filter to another language in the Translations view or even in the Languages view.

**Comment by Achal-Aggarwal** [comment]
I think the issue is that when we delete the only language listed in languages view then we can't list all languages of every client unless you select a language in the filter and then deselect it.
This is occurring because of https://github.com/joomla-projects/com_localise/blob/develop/component/admin/models/languages.php#L46

When the only listed language is deleted in languages view then $data array will be empty and then it will get data from user state.

Checkout this one https://www.youtube.com/watch?v=IIpqy3r-aNE

**Comment by infograf768** [comment]
Could you test adding:

```
unset($data['select']['tag']);
```

so that we get

```
    protected function populateState($ordering = null, $direction = null)
    {
        $app  = JFactory::getApplication();
        $data = $app->input->get('filters', array(), 'array');

        if (empty($data))
        {
            $data           = array();
            $data['select'] = $app->getUserState('com_localise.select');
            $data['search'] = $app->getUserState('com_localise.languages.search');
            unset($data['select']['tag']);
        }
        else
        {
            $app->setUserState('com_localise.select', $data['select']);
            $app->setUserState('com_localise.languages.search', $data['search']);
        }
[...]
```
