### ISSUE TITLE
Create updateservers

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#179]
This needs to be done:
https://github.com/joomla-projects/com_localise/blob/develop/localise.xml#L62

Maybe we can try to use the update servers for the localisation strings  xx-XX.com_localise. ini and sys.ini, in this same repository. I mean test Github as a platform for update servers.

**Comment by infograf768** [comment]
For the component, we do need indeed to define the updateservers and their necessary xml(s)

For the com_localise language packs, we are producing .zip of type="file" in which we can now include updateserver. (We have to check if type should be 'collection' or 'extension' btw. For example Webinstaller Update site uses 'extension') 

I guess the lang file manifest has to be present in the manifest folder for the updateserver to work, i.e each language has to be installed as a package for its updateserver specific xml be entered in the _updates_sites table and its id entered in _extensions and _update_sites_extensions

What I mean is that any language included in the language folder of the component would not be updatable, except when the component itself is. 
Only languages installed as pack would.

Here is an example of the final xml pack we would get now for com_localise:

```
<?xml version="1.0" encoding="UTF-8"?>
<extension type="file" version="3.0" method="upgrade">
    <name>fr-FRcom_localisefr-FR</name>
    <version>3.0.1</version>
    <creationDate>10/07/2014</creationDate>
    <author>Localise Team</author>
    <authorEmail></authorEmail>
    <authorUrl></authorUrl>
    <copyright>Copyright (C) 2012 - today Localise Team. All rights reserved.</copyright>
    <license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
    <packager></packager>
    <packagerurl></packagerurl>
    <description><![CDATA[French com_localise languagepack]]></description>
    <fileset>
        <files folder="admin/fr-FR" target="administrator/language/fr-FR">
            <filename>fr-FR.com_localise.ini</filename>
            <filename>fr-FR.com_localise.sys.ini</filename>
        </files>
    </fileset>
    <updateservers>
        <server type="collection" priority="1" name="localise github language">http://mysite.com/whatever.xml</server>
    </updateservers>
</extension>
```

I checked and the 3 tables are correctly populated.

So, to use com_localise github as updateserver for the lang packs we first would need to get a way to propose the zip for each language (where com_localise could export them) and make the necessary xmls. Has anybody done that before?

**Comment by infograf768** [comment]
May be useful to read:
http://stackoverflow.com/questions/20984019/automatic-extension-update-cant-handle-zip-file-from-github

**Comment by wilsonge** [comment]
That's a well known bug in com_installer. Akeeba adds &dummy=.zip to the
end of those urls to make it work.

**Comment by phproberto** [comment]
With a well forgotten patch for it: https://github.com/joomla/joomla-cms/pull/3182

#justSaying

**Comment by infograf768** [comment]
@phproberto 
 do you mean that when your PR is merged, we will be able to install pure zips from github repositories (I do not mean github-made zips, but specific zips we would add there)

**Comment by phproberto** [comment]
I think that's already possible now. I just tested and created packages to easily test it. 

On:
https://github.com/phproberto/joomla-updates/tree/master/plg_sys_mootable/downloads/1.1.0

There are two files:

[plg_sys_mootable_1.1.0.zip](https://github.com/phproberto/joomla-updates/raw/master/plg_sys_mootable/downloads/1.1.0/plg_sys_mootable_1.1.0-direct.zip) >> This is the standard file that uses my prefered way to release versions. I just add a git tag and link it in my [update server](https://github.com/phproberto/joomla-updates/blob/master/plg_sys_mootable/updates.xml). So everything is handled by github. In this case we would add a tag to a language repo and link it in the update server (**zip generated by Github**). 

[plg_sys_mootable_1.1.0-direct.zip](https://github.com/phproberto/joomla-updates/raw/master/plg_sys_mootable/downloads/1.1.0/plg_sys_mootable_1.1.0-direct.zip) >> I created this version for you. It uses a different [update server](https://github.com/phproberto/joomla-updates/blob/master/plg_sys_mootable/updateszip.xml) that is a direct link to a [zip file stored in github](https://github.com/phproberto/joomla-updates/blob/master/plg_sys_mootable/downloads/1.1.1/plg_sys_mootable_1.1.1.zip) (**zip generated manually**)

You can download both and install them to see how they update to v1.1.1

**Comment by infograf768** [comment]
After testing with Roberto, we found out that this would work for a direct xml but not when we first have a list (as we do for core lang packs).
I.e when we redirect in fonction of the language:
1. a common pack updateserver for all : 
https://github.com/infograf768/testupdate/blob/master/testupdate.xml
2. a specific update for the pack concerned:
https://github.com/infograf768/testupdate/blob/master/fr-fr_update.xml
See https://github.com/infograf768/testupdate  (All these xmls names are just for testing)
and where the .zip is here : https://github.com/infograf768/testupdate/releases

**Comment by nicksavov** [comment]
> So, to use com_localise github as updateserver for the lang packs we first would need to get a way to propose the zip for each language (where com_localise could export them) and make the necessary xmls. Has anybody done that before?

You should look into doing it with Phing instead. Each repository can have the same structure, then Phing can be used to generate the packages automatically.

> After testing with Roberto, we found out that this would work for a direct xml but not when we first have a list (as we do for core lang packs).

That sounds like a bug in the updater. The same packages should work for the Collection server type too. It should be reported and fixed in https://github.com/joomla/joomla-cms/issues. Then you'd be able to use it.

**Comment by phproberto** [comment]
We forgot to mention here that after further testing with JM we discovered it was a bug on his xml file.

Both update methods were working ok

**Comment by nicksavov** [comment]
Awesome :) Nice work, guys!

**Comment by infograf768** [comment]
I would not worry at this stage about com_localise lang packs, they do not concern much languages.
Let's first take care of the component updateservers first

**Comment by nicksavov** [comment]
Do you mean for https://github.com/joomla-projects/com_localise/ ? I can send in a pull request for it now if you'd like.

**Comment by infograf768** [comment]
Thanks, yes
update the localise.xml <updateservers>
+
a manifest xml 

Important, use:

```
<targetplatform name="joomla" version=".*"/>
```

**Comment by nicksavov** [comment]
All set:
https://github.com/joomla-projects/com_localise/pull/229

Let me know in the PR if you'd like me to change anything.
