### ISSUE TITLE
Changing name in package generates new

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#180]
See the video:

http://www.youtube.com/watch?v=scXvbsNjidY

Instead of renaming a package it generates a new one.

**Comment by infograf768** [comment]
I confirm the issue

**Comment by infograf768** [comment]
I think it is due to
https://github.com/joomla-projects/com_localise/pull/164
Before that, the field was readonly

The issue here is that we need to be able to change the name, specially when duplicating

**Comment by infograf768** [comment]
Tanks for testing the PR
