### ISSUE TITLE
Client or Location

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/com_localise#195]
I noticed that com_localise uses the term "client" to describe Site, Administrator, Installation Languages but in com_languages we use the term "location".

To me client is the wrong word and for consistency we should change this to client

![screenshot 2014-08-20 10 49 38](https://cloud.githubusercontent.com/assets/1296369/3979030/9a24d1a8-284f-11e4-9770-3116d8a160bb.png)
![screenshot 2014-08-20 10 49 52](https://cloud.githubusercontent.com/assets/1296369/3979031/9a302878-284f-11e4-8137-26082acf60f8.png)

**Comment by wilsonge** [comment]
I presume you mean we should change client to location? rather than client to client :P

**Comment by brianteeman** [comment]
Oops yes I mean we should use location throughout

**Comment by infograf768** [comment]
Fine with me. Will make a patch after we commit 196 and 197

**Comment by infograf768** [comment]
Done:
https://github.com/joomla-projects/com_localise/commit/e43d93a121f02a8200e78dd5034c199c7576858c

**Comment by brianteeman** [comment]
Thanks
