### ISSUE TITLE
Saving a new language behaves as Save and New

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/com_localise#198]
in the languages view, create a new language and save (not save and close).
The new language is indeed created but the redirect displays an empty form

**Comment by Achal-Aggarwal** [comment]
It is cms issue, here is the patch
https://github.com/Achal-Aggarwal/joomla-cms/compare/joomla:staging...Achal-Aggarwal:fix-com_local-198.diff
If it solves the problem here then I'll send a PR.
