### ISSUE TITLE
Warning: Attempt to assign property of non-object in Language view

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/com_localise#203]
#### How to reproduce?
- Go to Language edit view `administrator/index.php?option=com_localise&view=language&layout=edit&id=219&client=site&tag=en-GB`
- Change **Author Detail Tab->Author Url** set `www.joomla.org`
- You will get below warning.
  ![screenshot-by-nimbus](https://cloud.githubusercontent.com/assets/2002921/4023064/57ae08b0-2b71-11e4-8ff4-7dd45778c7e6.png)
#### Possible Solution

Method `loadFormData` return type should be an `Array` according to https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/form.php#L213
but here it returns an `Object` https://github.com/joomla-projects/com_localise/blob/develop/component/admin/models/language.php#L157 which is wrong and should be converted into an `array`.

**Comment by infograf768** [comment]
This one is also because the field is now URL.
Change the url to:
http://www.joomla.org
and no more error.

**Comment by gunjanpatel** [comment]
@infograf768 Yes I get that. But my point is not with wrong **Author Url** but I mean to say when we have an error in saving, we will get this warnings. :)

**Comment by infograf768** [comment]
Indeed.

**Comment by infograf768** [comment]
can you test https://github.com/joomla-projects/com_localise/pull/209 ?

**Comment by infograf768** [comment]
Closing as it was solved by #209
Thanks
