### ISSUE TITLE
Date notification "now" in form "Create new Language"

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/com_localise#232]
Components > Localise > Languages > Create new language
The Creation Date has "now" as default field,
after saving, the date field stores "now" as date.

In my example file /administrator/language/ex-EX/ex-EX.xml
the date is hardcoded stored as "now":
<creationDate>now</creationDate>

I think it would be better to display the current system date instead.

**Comment by wilsonge** [comment]
Fix in #243

**Comment by infograf768** [comment]
See discussion in https://github.com/joomla-projects/com_localise/pull/243
