### ISSUE TITLE
Localise > Languages, Improve order & content of columns

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/com_localise#234]
The order of the columns in the list of languages differs from the order of the columns in the Language Manager:

Component > Localise > Languages
Language name | Location | Default | Files | Version | Date | Author
[ex-EX] [example language]([Example Country]) | Administrator | __ | __ | 3.3.6 | now  | Peter Martin

Compare with 
Extensions > Language Manager >
Language | Language Tag | Location  | Default | Version | Date | Author  | Author Email
English (United Kingdom)| en-GB | Administrator | __ | 3.4.0   | 2013-03-07| Joomla! Project | admin@joomla.org

"Language name" contains also the language code: [ex-EX] [example language]([Example Country])
I would propose to put the language code [ex-EX] in it's own column, just like e.g. Joomla's Content Articles 

And to use the same order as in Languages Manager

Language | Language Tag | Location | Default | Version | Date | Author
[example language]([Example Country])  | [ex-EX]   | Administrator | __ | 3.3.6   | now  | Peter Martin

Not sure what the best place for "Files" would be...

**Comment by infograf768** [comment]
we can easily have
Language (name) | Language Tag | Location | Files | Default | Version | Date | Author
Would that fit?

**Comment by pe7er** [comment]
yes, I think that it would be ok.

**Comment by infograf768** [comment]
This?
![screen shot 2014-11-10 at 12 19 09](https://cloud.githubusercontent.com/assets/869724/4989799/c0ffb49e-697e-11e4-9488-fb389ab3332a.png)

**Comment by infograf768** [comment]
See and test:

https://github.com/joomla-projects/com_localise/pull/246
