### ISSUE TITLE
Packages overview shows very little information

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/com_localise#238]
See Component > Localise > Packages
The list of packages only show: Title + Type

Is it possible to add somewhat more information about the packages?
I am thinking about: language tag, location (admin/site) and creation date (e.g file date of xml/zip file) ?

**Comment by infograf768** [comment]
This manager only displays the internal to com_localise packages, not the .zip packages.
Therefore, we can't show the date which is created when the .zip is created.
The location is both site/admin for core packages, it can be one, the other, or both for a 3rd party extension.
Looking how to get the Tag and version now

**Comment by infograf768** [comment]
please test
https://github.com/joomla-projects/com_localise/pull/247
