### ISSUE TITLE
Autofill the creation date field when creating new language

### ISSUE THREAD

**Issue by BrittaStender** [joomla-projects/com_localise#241]
![creation-date-bug](https://cloud.githubusercontent.com/assets/2777672/4965870/487c5c78-679b-11e4-9073-9025c010861d.png)

It states "now" as standard text. Couldn't it contain the actual date instead?

**Comment by wilsonge** [comment]
Fix in #243

**Comment by infograf768** [comment]
Look at discussion in https://github.com/joomla-projects/com_localise/pull/243
