### ISSUE TITLE
Move all JRequests to JInput

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#25]
There is still some uses of JRequests, needs to be moved to JInput https://github.com/joomla-projects/com_localise/search?q=JRequest&ref=cmdform&type=Code

**Comment by javigomez** [comment]
There is still a couple of places were JRequest needs to be switched to Jinput https://github.com/joomla-projects/com_localise/search?q=jrequest&type=Code

Assigning it to @gunjanpatel  for tomorrow working table

**Comment by infograf768** [comment]
This has been done, closing
