### ISSUE TITLE
IMPORTANT: Needs update error parsing to follow Joomla core.

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/com_localise#257]
Grace to the new minimum  PHP version for 3.x, we now can include double doublequotes in the values instead of `"_QQ_"`. For example in a URL or class:
`<a href="_QQ_"http://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html"_QQ_">`
can be written
`<a href="http://community.joomla.org/blogs/leadership/1798-raising-the-bar-on-security.html">`
same for a span:
`<span class="_QQ_"term"_QQ_">`
can be 
`<span class="term">`
`"_QQ_"` can still be used

In text, for example to highlight a term, we can use
`"_QQ_" special wording"_QQ_"`
or
`&quot;`special wording`&quot;`

See Joomla patch here which corrects the debug to allow for that:
https://github.com/joomla/joomla-cms/pull/5862

We need to change in com_localise the way we throw errors to cope with this.

**Comment by mbabker** [comment]
Just at a quick glance, it looks like your validator is the same regex that JLanguage was using before (see https://github.com/joomla-projects/com_localise/blob/develop/component/admin/models/translation.php#L380).  So you should be able to update this section to match the updated code in JLanguage.

**Comment by infograf768** [comment]
@mbabker 
We also have a parseini.js

**Comment by infograf768** [comment]
Closing in favor of https://github.com/joomla-projects/com_localise/issues/260 which is a WIP
