### ISSUE TITLE
Folders and files starting by --

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#26]
There are several files and folders starting by "--" 

I haven't check what does it means but much probably we are not using it and can be removed. See this examples:

https://github.com/joomla-projects/com_localise/tree/develop/administrator/components/com_localise/models

**Comment by infograf768** [comment]
--archive.php is the only one which does not exist without the "--"

**Comment by javigomez** [comment]
Closing since this was fixed at #42
