### ISSUE TITLE
Use of indefined constant error

### ISSUE THREAD

**Issue by Valc** [joomla-projects/com_localise#263]
Trying to edit a file to delete the next 3.4 release i am getting this notice:

![captura de pantalla de 2015-01-31 23 25 16](https://cloud.githubusercontent.com/assets/417247/5990069/03347a18-a9a1-11e4-94f6-55fb8dbc1dc9.png)

Notice: Use of undefined constant LOCALISE_ADMINISTRATOR - assumed 'LOCALISE_ADMINISTRATOR' in /var/www/3.4/administrator/components/com_localise/helpers/localise.php on line 592

We have:
$path = $client == 'administrator' ? LOCALISEPATH_SITE : LOCALISE_ADMINISTRATOR . "/language/$tag/$tag.$filename.ini";

It should be:
$path = $client == 'administrator' ? LOCALISEPATH_SITE : LOCALISEPATH_ADMINISTRATOR . "/language/$tag/$tag.$filename.ini";

Regards.

**Comment by Valc** [comment]
Also noticed that under this case (seems that is due it is a file to delete), i am able to edit in raw mode and take a look to the string within the translated file, but in normal edition mode, no one string is present (is blank or empty of keys).
No idea about why or if this is the expected result.

**Comment by infograf768** [comment]
Corrected directly to LOCALISEPATH_ADMINISTRATOR indeed. Thanks!

https://github.com/joomla-projects/com_localise/commit/ad703a8b8cea4515caf9ebec08ae89ecc0780aaf

> Also noticed that under this case (seems that is due it is a file to delete), i am able to edit in raw mode and take a look to the string within the translated file, but in normal edition mode, no one string is present (is blank or empty of keys).
> No idea about why or if this is the expected result.

All depends on the choice in Options
If there is no original file in the reference language (lib_phpmailer.sys.ini here and reference en-GB) then this is what one should get if the file is present in the Target language:
![screen shot 2015-02-05 at 09 01 35](https://cloud.githubusercontent.com/assets/869724/6056741/af65b3d4-ad15-11e4-8ad7-118694321a25.png)

Then when clicking on the "normal" edit, nothing will show as there is no reference file.
Normal behaviour. What could be done is to add a message/Notice in that case
