### ISSUE TITLE
feature request: a new button for "show un-translated lines only"

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#280]
Sometimes when I update a language translation, for example, it has more than 1,000 lines, and there are only 7 or 10 new lines added in the new version. Well, com_localise will tell me that there are 7 or 10 lines of translation missing, but maybe those new lines are not at the beginning, neither at the end, they just scattered in those 1000 lines! How can I find out these new lines quickly?

I think a new button of "show un-translated lines only" will solve this.

Please add such a button.

Thank you.

**Comment by infograf768** [comment]
See proposed PR
https://github.com/joomla-projects/com_localise/pull/277

where this is implemented.
The PR is not complete in the sense that we can't mark string per string a changed string as translated.

**Comment by infograf768** [comment]
Here is a screenshot:
![screen shot 2015-08-18 at 09 40 01](https://cloud.githubusercontent.com/assets/869724/9324731/32aaeb82-458d-11e5-9824-b5cbf9042e31.png)
