### ISSUE TITLE
com_localise and Sobipro: one of you should be wrong

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#281]
I tried to translate Sobipro (com_sobipro) from  www.sigsiu.net with com_localise. And com_localise indicates that there is something wrong with the English language file. The source code is:

SP.PERMISSIONS.DELETE_*="delete any"

Well, it seems that com_localise think "dot" and "star" symbols should NOT in language Key.

I had posted this issue on sobipro forum:

https://forum.sigsiu.net/sobipro-public-community-board/sobipro-language-files-does-not-match-the-joomla-2-5-standard/

But they said: Joomla language file standard ALLOWS those symbols in language Key. So they have nothing to change.

Ok, now it is up to com_localise. Why you think those special characters should NOT be in the language key?

One of you should be wrong.

If com_localise was wrong, please fix this so that I can validate my translations with it.

Thank you.

**Comment by infograf768** [comment]
It is the star which is creating issues and, for your info, Joomla core is also stating the star in a constant as a Parsing issue although the translation works fine. 
To check, just enable Debug language and go on a page where you have such strings.

I am now making a patch for com_localise and will propose a patch to core.

**Comment by infograf768** [comment]
As I will update com_localise when we get to 3.5.0-prerelease in a few days, you can now patch with this (replace lines with a minus sign by these with a + sign and take off the +:

```
diff --git a/component/admin/models/translation.php b/component/admin/models/translation.php
index f7bfaa3..b2bb09d 100644
--- a/component/admin/models/translation.php
+++ b/component/admin/models/translation.php
@@ -391,5 +391,5 @@
                        $lineNumber++;

-                       if (!preg_match('/^(|(\[[^\]]*\])|([A-Z][A-Z0-9_\-\.]*\s*=(\s*(("[^"]*")|(_QQ_)))+))\s*(;.*)?$/', $line))
+                       if (!preg_match('/^(|(\[[^\]]*\])|([A-Z][A-Z0-9_\*\-\.]*\s*=(\s*(("[^"]*")|(_QQ_)))+))\s*(;.*)?$/', $line))
                        {
                            $this->item->error[] = $lineNumber;
@@ -666,5 +666,5 @@
                    }
                    // Key lines
-                   elseif (preg_match('/^([A-Z][A-Z0-9_\-\.]*)\s*=/', $line, $matches))
+                   elseif (preg_match('/^([A-Z][A-Z0-9_\*\-\.]*)\s*=/', $line, $matches))
                    {
                        $header     = false;
@@ -701,5 +701,5 @@
                        continue;
                    }
-                   elseif (!preg_match('/^(|(\[[^\]]*\])|([A-Z][A-Z0-9_\-\.]*\s*=(\s*(("[^"]*")|(_QQ_)))+))\s*(;.*)?$/', $line))
+                   elseif (!preg_match('/^(|(\[[^\]]*\])|([A-Z][A-Z0-9_\*\-\.]*\s*=(\s*(("[^"]*")|(_QQ_)))+))\s*(;.*)?$/', $line))
                    {
                        $this->item->error[] = $lineNumber;
@@ -966,5 +966,5 @@
            while (!$stream->eof())
            {
-               if (preg_match('/^([A-Z][A-Z0-9_\-\.]*)\s*=/', $line, $matches))
+               if (preg_match('/^([A-Z][A-Z0-9_\*\-\.]*)\s*=/', $line, $matches))
                {
                    $key = $matches[1];
```

```
diff --git a/media/com_localise/js/parseini.js b/media/com_localise/js/parseini.js
index 71e8256..0418ebc 100755
--- a/media/com_localise/js/parseini.js
+++ b/media/com_localise/js/parseini.js
@@ -37,5 +37,5 @@
            else if (sol && /[A-Z_\.]/.test(ch) && state.position === 'identifier')
            {
-               stream.eatWhile(/[A-Z_\.\-0-9]/);
+               stream.eatWhile(/[A-Z_\*\.\-0-9]/);
                state.position = "equal";
                blacklist = ["YES", "NO", "NULL", "FALSE", "ON", "OFF", "NONE", "TRUE"];
```

**Comment by infograf768** [comment]
Please also test
https://github.com/joomla/joomla-cms/pull/8356

**Comment by infograf768** [comment]
New release ready. Closing this.
