### ISSUE TITLE
feature request: a button to "only show untranslated lines"

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#283]
Sometimes I have such a situation: a language file contains more than 2k lines, and the new version added about 20 lines. But, these 20 new lines are not at the end of that language file, nor at the beginning of the language file. Instead, they were scattered inside those 2k+ lines!

This com_localise tool can only tell me "how many lines not translated", but it can not show me "where are they".

Though this tool can show untranslated lines with dark red background color in the input box, but, how can I quickly find those 20 lines among those 2K+ lines? It is not easy for human eyes to catch each of them when scroll the page for more than 20 screens!

My suggestion:

add a button named "only show untranslated lines", if clicked, those translated lines will be hidden, and only untranslated lines shown there one after one. This means, if I have 20 lines not translated, after clicking that button, there will be only 20 lines shown on the page, I can quickly translate them WITHOUT scroll the page again and again to find them!

Thank you.

**Comment by infograf768** [comment]
@baijianpeng 

Please install this update via extension=>Install
https://www.dropbox.com/s/0uz1ioomutztb0x/com_localise-4.0.15-beta.zip?dl=0

This is a beta which includes the functionnality of this PR:
https://github.com/joomla-projects/com_localise/pull/277

A new table is created when updating.
`#__localise_revised_values`

As the functionnality still needs cleaning, I can't release it as a pure 4.0.15-dev

You will find :
A new filter in the translations view:
![screen shot 2015-12-18 at 10 34 51](https://cloud.githubusercontent.com/assets/869724/11893745/1afe72a6-a573-11e5-9939-3cbe06da3995.png)

The "Incomplete" filtering will help you display directly the files modified or with new strings for Core.
For an extension, ONLY the files with new strings.

and some new filters in the edit translation view
![screen shot 2015-12-18 at 10 37 15](https://cloud.githubusercontent.com/assets/869724/11893808/73c6ec4c-a573-11e5-937a-cbdb73e8989f.png)
![screen shot 2015-12-18 at 10 37 29](https://cloud.githubusercontent.com/assets/869724/11893815/78ad4b52-a573-11e5-8b7a-e4b5d2324a15.png)

The new "Modified" filter deals with the new Options of the component which is ONLY aimed at improving the updating of core packs. You do not need to enable it when you only deal with an extension.
This screenshot to show you how I have set it up for core needs:

![screen shot 2015-12-18 at 10 43 49](https://cloud.githubusercontent.com/assets/869724/11893930/4d298aee-a574-11e5-92b5-1afac78f5435.png)

IMPORTANT:
When you edit a file, use a filter and modify a translation, you should Save before doing another filtering.

**Comment by joomlagate** [comment]
Thank you. I installed that 4.0.15 beta version and then found some thing wrong:
1. When show the file list view, though my translation is "uncomplete", but it shows complete (yellow tick) status! Take a look at the screenshot showing below, there were still 45 strings not translated, but that file was recognized as "complete".

![wrongly-complete-status](https://cloud.githubusercontent.com/assets/1249063/11898853/fb3bcdde-a5d5-11e5-9e1c-0cd0a8ddd60c.png)
1. when enter the file content, in the filter drop-down list, the "untranslated" is not selectable. You can see that option is in slightly gray color.

![untranslated-unselectable](https://cloud.githubusercontent.com/assets/1249063/11898953/ae80b346-a5d6-11e5-8952-76f8108cc377.png)
1. If I choose "unchanged" from that filter list, many tabs show up ( this is for the com_localise's language file). I know those tabs are generated from those sub-titles surrounded by square brackets in the language file. But, why those "empty" sections will also show up? Note: they are "empty" because I choose "unchanged" as the filter option. So, if one section has no strings matching this filtering criteria, that section will be "empty". So I think , we should HIDE those empty sections.

![empty-tab-not-hidden](https://cloud.githubusercontent.com/assets/1249063/11899024/4b585174-a5d7-11e5-923d-5cb7bdc0bc5c.png)

In fact, I think when I choose a filter option, those sections should be merged, to show all matching strings together. Because, if not showing in this way, I have to click many times to check each section, one after one.

**Comment by infograf768** [comment]
This is why I said 4.0.15 is not ready yet. We have some bugs.
What happens for now is that a file which was incomplete is set as complete as soon as one uses the Save button. Therefore when one has not finished yet translating and postponing some translations for later on, all strings are set as Translated (except the Modified core ones as these need ticking the "Revised" check box).
Even when un-ticking the "Complete" check box, it does save as complete.

Concerning the sections, it is a rather petty aspect. Only com_localise language files are using this. Not urgent imho.

**Comment by infograf768** [comment]
Here is a screen shot of a core pack file (3.4.4 pack) which has not been updated yet to 3.4.6 to show it works before saving it.

![screen shot 2015-12-19 at 08 48 01](https://cloud.githubusercontent.com/assets/869724/11912078/7bfe0aa2-a62d-11e5-81d6-7315b901134f.png)

**Comment by joomlagate** [comment]
This is not good. Infact, I always check and validate translations with
com_localise, but after "save" file, I do my translating work with
EmEditor, I do not like to translate one after one in the Localise
component, because it does not offer features like "search and replace",
which are very common in an TXT editor software.

2015-12-19 15:45 GMT+08:00 infograf768 notifications@github.com:

**Comment by infograf768** [comment]
I have now merged https://github.com/joomla-projects/com_localise/pull/277 where the "Complete" issue is solved. I.e. one has to set the file as Complete before saving, when desired.

**Comment by infograf768** [comment]
I will soon release a new version of the component.

**Comment by infograf768** [comment]
@baijianpeng 

Please use now the new release:
https://github.com/joomla-projects/com_localise/releases
