### ISSUE TITLE
can not save "zh-CN.ini" file

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#284]
Today when I trying to translate the file "**zh-CN.ini**" (Joomla main language file of backend) on Joomla 3.5.0 RC version, I noticed that com_localise v4.0.15-beta (I forgot where did I downloaded this version, maybe from this repository) can NOT save this file. After I click on "Save and Close" button, the page just refreshed, without saving nor closing. 

Please check this and fix it.

Thank you.

**Comment by infograf768** [comment]
I proposed it to you here:
https://github.com/joomla-projects/com_localise/issues/283#issuecomment-165732547

It works OK here on staging (3.5.0 RC)

Do you have any error in your php logs?

**Comment by joomlagate** [comment]
A little weird, I can save the "zh-CN.ini" file of frontend, but not the backend one.

There is no records in PHP logs.

update:

Well, now I find out the cause:

When I check the Apache log (I use XAMPP local server on my PC), the last line is:

> [Fri Mar 11 19:28:40.231050 2016] [:error] [pid 22348:tid 1880] [client ::1:60606] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer: http://localhost/j3/administrator/index.php?option=com_localise&view=translation&layout=edit&id=275&client=administrator&tag=zh-CN&filename=joomla&storage=global

So I edited my php.ini file, and set it to:

`max_input_vars = 10000
`

Then I restarted Apache and tried to save the same file, this time it was successfully saved.

Thank you.

**Comment by joomlagate** [comment]
However, when I checking the php.ini file, that option was commented out with a ";" symbol at the beginning of that line.  Why a commented-out option will take effect?

**Comment by mbabker** [comment]
PHP will use a default value if the option isn't explicitly set.

**Comment by infograf768** [comment]
I had personnaly set the value to
`max_input_vars = 2786`

as the issue was not only for Simplified Chinese.

**Comment by infograf768** [comment]
I just merged this PR to cope with such issue.
https://github.com/joomla-projects/com_localise/pull/287
