### ISSUE TITLE
Sorting broken in Translations view

### ISSUE THREAD

**Issue by infograf768** [joomla-projects/com_localise#294]
As title says, there is no change when switching from ascending to descending.

**Comment by Valc** [comment]
Seems It is due the filter never is sending an '1': it is sending an "asc", "desc" or an empty value:
At ../models/translations.php we have:

```
            $direction = -1;

            if ($this->getState('list.direction'))
            {
                $direction = 1;
            }
```

Replaced by this one the stuff seems is working:

```
            if ($this->getState('list.direction') == "asc" || $this->getState('list.direction') == "")
            {
                $direction = 1;
            }
            else
            {
                $direction = -1;
            }
```

But if the idea is get 1 or -1 values is required search where the "desc" or "asc" are inserted (no idea in this moment).

One time solved there seem that the original code will be working right.

Regards.

**Comment by infograf768** [comment]
I have another solution, implementing at the same time searchtools. :smiley:
Will post here when I have a PR.

**Comment by Valc** [comment]
Great :smiley:

**Comment by infograf768** [comment]
Please test
https://github.com/joomla-projects/com_localise/pull/295

**Comment by infograf768** [comment]
Closing as we have a patch
