### ISSUE TITLE
EOL Issues with raw mode

### ISSUE THREAD

**Issue by Valc** [joomla-projects/com_localise#297]
#### Steps to reproduce the issue

1 Edit any file with raw mode and save and close it.
2 Edit the same file in normal mode and save and close it.
3 Edit the same file in raw mode and go to the end of the file lines: before the last string now is added a section "[New strings]" when not true.
#### Expected result

It will be the same than edit in normal mode: the file is mounted with  "\n"
#### Actual result

Editing files in raw mode make save the files without Unix EOL, and one time the "BOM!" issues are inserted editing in raw mode then are making fail the normal mode saving files.
#### System information (as much as possible)

Linux, so my files are saved as default as UNIX/Linux EOL.
#### Additional comments

To catch the issue the MSP (Enabling the system messages options related with BOM and EOL) has been helping me to found whats was happening, due at the begin this was hard to catch.

The stuff is that edit in raw mode save the files without UNIX/Linux EOL, and my files are for sure UNIX/Linux EOL before edit it in raw mode.

After test the issue:
![eol](https://cloud.githubusercontent.com/assets/417247/14041098/1af30338-f26e-11e5-8525-28593062360c.png)

Regards.

**Comment by infograf768** [comment]
I can't reproduce these issues here on Macintosh.

**Comment by infograf768** [comment]
What I mean is that I can see your es-ES.com_ajax.ini is Windows EOL and es-ES.com_contacts.ini has [New Strings] on top of the file, but I can't reproduce your issue with my fr-FR files or Italian files

**Comment by Valc** [comment]
Can you test saving one of you language files as UNIX/Linux EOL?

**Comment by infograf768** [comment]
@Valc
Using 4.0.16-dev, I edit your 3.5.0.1 files (normal way) and save, and they are corrected:
no more Windows EOL for Ajax, no more [New Strings] on top for the other files concerned.

My files are always Unix.

**Comment by infograf768** [comment]
Are'nt you using a custom com_localise and not 4.0.16-dev?

**Comment by Valc** [comment]
No, i am updated today to .16. My other "complex develop" branch i know is bugged but i am waitting for more free time.
Noticed that saving in normal mode the issue about EOL is gone... But editing again in raw mode and saving for you is not coming back?

**Comment by infograf768** [comment]
Nope.

**Comment by infograf768** [comment]
wait, indeed it does saves with Windows EOL when saving in Raw mode.

**Comment by Valc** [comment]
Yes, that i means: the files starts before edit in my format  and after save  In raw mode become in not UNIX EOL.

**Comment by infograf768** [comment]
@Valc
I think I found out the issue:
It is due to Codemirror.

To test I edited in Beez template through the Joomla interface the file component.php
It saved as UTF8 No BOM (so far so good) BUT with Windows EOL (CRLF)

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/issues/9592

**Comment by Valc** [comment]
Well founded.
If they have solved from the main cause we only needs wait that patch to resolve the issue here.

**Comment by Valc** [comment]
Please, also revise:
open and save in normal mode that language file converted to windows format.
now open in  raw mode and go to the end of the file: Is there a [New strings] section to you?
Due this one only can happens due the same issue also will be solved by same patch, but means than mix this type of formats can generate internal mistakes mounting the file to save in normal mode.

**Comment by infograf768** [comment]
> now open in raw mode and go to the end of the file: Is there a [New strings] section to you?

No.

I may have found a solution for the EOL though for com_localise when saving in raw mode.

Please test adding this
`$contents = str_replace(array("\r\n", "\n", "\r"), "\n", $contents);`
just before
`$return = JFile::write($path, $contents);`

https://github.com/joomla-projects/com_localise/blob/develop/component/admin/models/translation.php#L1400

and let me know.

**Comment by Valc** [comment]
Yes, your mod is working and solve the issue at com_localise.

I think that for us the issue starts at line 1193 of same file, due the raw content is accessing by that way such as is coming from the codemirror:

```
if (array_key_exists('source', $data))
{
$contents = $data['source'];
}
```

But where you have added the line ensures make work any other odd scenario: so for me perfect.

Regards

**Comment by infograf768** [comment]
Please mark this PR as OK:
https://github.com/joomla-projects/com_localise/pull/298

It may work even when codemirror is corrected.
