### ISSUE TITLE
Create the package generator

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#3]
This tool will generate the language packages from the files in the system

Currently we have this view: administrator/index.php?option=com_localise&view=packages

![screen shot 2014-05-30 at 14 11 03](https://cloud.githubusercontent.com/assets/1375475/3130197/6ce9ae62-e7f3-11e3-977e-a0b4508af924.png)

The goal of this view is to allow us to generate a language package, right now is not working well but it shouds allow us to:
- [ ] Generate a language package oncluding only language files for SITE
- [ ] Generate a language package oncluding only language files for ADMIN
- [ ] Generate a language package oncluding only language files for SITE & ADMIN

See comment of Jean Marie below

**Comment by infograf768** [comment]
At this stage we need to:
- create an install.xml for site and different one for admin
- then .zip the site folder, then zip the admin folder
- add a pkg xml with 4 digits version and .zip the 3 parts.

See: http://docs.joomla.org/J3.2:Making_a_Language_Pack_for_Joomla

**Comment by infograf768** [comment]
Also see:
https://github.com/joomla-projects/com_localise/issues/15

**Comment by infograf768** [comment]
As explained, we need 2 types of packages
One for Core, which has to contain both Site and Admin (although some admin files may not be translated for "Site only" packs.

Although both may need improvements (Specially Core), this is now implemented.
https://github.com/joomla-projects/com_localise/issues/106
