### ISSUE TITLE
detect language files not in standard language folder path

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#304]
#### Steps to reproduce the issue

Install free module RT RokSprocket (download from http://www.rockettheme.com/joomla/extensions/roksprocket ) on Joomla 3, look at this folder:

**/components/com_roksprocket/layouts/**

Every subfolder in that folder has a sub-subfolder named "language", in those language folders, you will find en-GB folder and ini format language files inside.

But, com_localise can not detect these language files, because they are neither in the /language folder, nor in the /component/com_roksprocket/language folder.
#### Expected result

I hope com_localise will detect further, scan every folder to find out every language file. So I can check, compare and validate my translations with those original English language files.
#### Actual result

Current com_localise v4.0.16dev can not detect those language files which were not uploaded to the standard language folder path.
#### System information (as much as possible)

Jooma  v3.5.1
com_localise v4.0.16 dev
RT RokSprocket module v2.1.12
PHP  v5.4
#### Additional comments

Could you please improve com_localise to support translating of RT RokSprocket module?

Thank you.

**Comment by uzielweb** [comment]
This module is wrong.
The language folders is needed in the default and not in
/modules/your_module/language.

2016-04-20 7:30 GMT-03:00 baijianpeng notifications@github.com:

> Steps to reproduce the issue
> 
> Install free module RT RokSprocket (download from
> http://www.rockettheme.com/joomla/extensions/roksprocket ) on Joomla 3,
> look at this folder:
> 
> _/components/com_roksprocket/layouts/_
> 
> Every subfolder in that folder has a sub-subfolder named "language", in
> those language folders, you will find en-GB folder and ini format language
> files inside.
> 
> But, com_localise can not detect these language files, because they are
> neither in the /language folder, nor in the
> /component/com_roksprocket/language folder.
> Expected result
> 
> I hope com_localise will detect further, scan every folder to find out
> every language file. So I can check, compare and validate my translations
> with those original English language files.
> Actual result
> 
> Current com_localise v4.0.16dev can not detect those language files which
> were not uploaded to the standard language folder path.
> System information (as much as possible)
> 
> Jooma v3.5.1
> com_localise v4.0.16 dev
> RT RokSprocket module v2.1.12
> PHP v5.4
> Additional comments
> 
> Could you please improve com_localise to support translating of RT
> RokSprocket module?
> 
> Thank you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joomla-projects/com_localise/issues/304

## 

_Teu Ponto de Partida Para o Mundo_

_www.pontomega.com.br http://www.pontomega.com.br_

_Email: contato@pontomega.com.br contato@pontomega.com.brSKYPE:
usiel.almeida.oliveiraGoogle PLUS:
https://plus.google.com/114500889234835860287/
https://plus.google.com/114500889234835860287/Facebook:
http://pt-br.facebook.com/pages/Ponto-Mega/212467028765454
http://pt-br.facebook.com/pages/Ponto-Mega/212467028765454Twitter:
http://twitter.com/pontomega http://twitter.com/pontomega_

**Comment by infograf768** [comment]
Not only these language files are not placed where they should, but they do not obey to the correct standard naming (ex: en-GB.roksprocket_layout_grids.ini)
As the main com_roksprocket/site/language/en-GB/en-GB.com_roksprocket.ini contains only one string, it means these devs did a bad job.
I'm afraid we can't do anyhting in com_localise for these.
Closing.

**Comment by joomlagate** [comment]
OK, I will try to persuade RT developers to modify their file structures and codes.

Thank you.
