### ISSUE TITLE
how to hide the "check if you set complete" pop-up warning?

### ISSUE THREAD

**Issue by joomlagate** [joomla-projects/com_localise#309]
#### Steps to reproduce the issue

Each time I save the translation in com_localise, after click on the Save button, there will show a pop-up dialog remind me to check if I had set "complete" on the details Tab.

This pop-up is annoying, it forces me to click the "OK" button on that pop-up message,  but there is no option to disable or hide it.
#### Expected result

I hope there is an option to allow me totally hide that pop-up message.
#### Actual result

I did not find any option to do so.
#### System information (as much as possible)

Joomla  3.5.1
Localise 4.0.17 dev
#### Additional comments

Thank you.

**Comment by infograf768** [comment]
Hmm, this imply getting the php parameter into js.

**Comment by infograf768** [comment]
I can do that, but, again, another parameter...

**Comment by infograf768** [comment]
@Valc 
The code is ready here (quite simple). Do you agree I add this parameter in the component Options?

**Comment by Valc** [comment]
I think that if you have to include it as an option it should be enabled by default, due for me that reminder is very useful (It saves me time and mistakes). But, if other persons does not like use the popup window they can go to disable it by Options and also can get their taste with that popup.

Regards, Valc.

**Comment by infograf768** [comment]
Sure, would be enabled by default.
Will make a PR

**Comment by infograf768** [comment]
Please test https://github.com/joomla-projects/com_localise/pull/310
