### ISSUE TITLE
Please update language files for brazilian portuguese in github

### ISSUE THREAD

**Issue by uzielweb** [joomla-projects/com_localise#319]
The language files are very old

I have update all language resources files in Transifex
I have created a package for Brazilian Portuguese to latest version. Please update in GitHub
The link for download is: https://www.pontomega.com.br/images/downloads/pt-BR_localise_4.0.31-dev.zip

@infograf768

**Comment by infograf768** [comment]
@uzielweb
Done and sorry for delay. Had not received mail.
