### ISSUE TITLE
Error after installing component

### ISSUE THREAD

**Issue by gunjanpatel** [joomla-projects/com_localise#32]
I have create package using `sh build.sh` file and tried to install `packages/com_localise.zip`
Installed successfully but after installing found error below. 
Did I forget something?

![error](https://cloud.githubusercontent.com/assets/2002921/2900965/8c6dddee-d5ce-11e3-8d42-41f5461f63e5.png)

**Comment by mbabker** [comment]
Looks like a malformed SQL query in the code somewhere.

**Comment by gunjanpatel** [comment]
Pull Request #33 fixes this issue. But found **Fatal error: Call to undefined method SimpleXMLElement::name() in /var/www/html/jcms3/administrator/components/com_localise/models/language.php on line 196** after fixing. (not related, but just reporting)
