### ISSUE TITLE
 it will not work without reading, writing and renaming rights on the language directories and files.

### ISSUE THREAD

**Issue by Sukinoz** [joomla-projects/com_localise#328]
i am trying to copy Spanish-Spain to create Spanish-Mexico

But, I dont understand what do you mean with this sentence:

>  it will not work without reading, writing and renaming rights on the language directories and files.

Thanks

**Comment by infograf768** [comment]
I was speaking about the necessary permissions for the language directory and files.

**Comment by infograf768** [comment]
It is real easy now in com_localise to create a pack containing the same translations values as another existing pack with a different ISO code.
Did you succeed or do you need help?

**Comment by Sukinoz** [comment]
Success!
Should be core for joomla 4!
