### ISSUE TITLE
Image "author" in readme has errors and can't be displayed.

### ISSUE THREAD

**Issue by sloanthrasher** [joomla-projects/com_localise#329]
#### Steps to reproduce the issue
View the readme on GitHub

#### Expected result
Image is displayed correctly in browser

#### Actual result
Browser displays an error message:
The image “https://raw.githubusercontent.com/joomla-projects/translate-joomla/master/images/structure/actors.png” cannot be displayed because it contains errors.

**Comment by infograf768** [comment]
I have taken off that part from the readme as the image it refers to does not exist anymore
