### ISSUE TITLE
Localise not working, even not opening, after Joomla update to 3.8.6

### ISSUE THREAD

**Issue by ModDM** [joomla-projects/com_localise#330]
Dear Sir / Madam,

Previous time you asked these questions, so let me answer those:
Which Joomla version are you using?
- 3.8.6

And which languages are installed?

- Dutch (nl-NL)
- English (en-GB)

Although my previous issue was already solved very soon, it seems Localise is not working when you update to Joomla 3.8.6. (This is a new issue). I used to work successfully before the update to this Joomla version, but after it, it stopped. Can you as soon as possible fix your extension for this Joomla version? (Or if the problem is something else, I'm interested in any solution of course).

Here is the error seen when you install Joomla to 3.8.6 and try to open Localise component in Joomla backend:

Warning: require_once(joomla\administrator/components/com_localise/vendor/autoload.php): failed to open stream: No such file or directory in joomla\administrator\components\com_localise\localise.php on line 23

Fatal error: require_once(): Failed opening required 'joomla\administrator/components/com_localise/vendor/autoload.php' (include_path='.;C:\php\pear') in joomla\administrator\components\com_localise\localise.php on line 23

Localise will not open.

Your help to make it work will be greatly appreciated. Localise is an important extension for us.

With kind regards,

ModDM

**Comment by ModDM** [comment]
My Localise version: 4.0.32-dev

**Comment by ModDM** [comment]
Strange. For some reason the whole vendor folder was missing. I uploaded the folder again and now it's solved. Depending on what you prefer you can close or delete this ticket / rename it / whatever you want (because while looking back, the title gives incorrect information - your extension works correct).

**Comment by infograf768** [comment]
Tks for reporting and finding the issue. Closing indeed.
