### ISSUE TITLE
Missing button delete at toolbar

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#38]
There is a delete button before every element in the "languages list":

![screen shot 2014-05-20 at 21 23 33](https://cloud.githubusercontent.com/assets/1375475/3032151/2d42a36e-e054-11e3-90bd-aab45a52bd10.png)

But as the normal Joomla toolbar, I suggest to create a delete button in toolbar:
![screen shot 2014-05-20 at 21 25 27](https://cloud.githubusercontent.com/assets/1375475/3032172/68d2c738-e054-11e3-8b1a-369cc4ac1a49.png)

**Comment by infograf768** [comment]
I think it is safer to not let multiple language.xml be deleted.
Roberto patched and delete now works.
