### ISSUE TITLE
Remove language doesn't works

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#39]
Issue at: administrator/index.php?option=com_localise&view=languages

When I click on removing a language:
![screen shot 2014-05-20 at 21 27 54](https://cloud.githubusercontent.com/assets/1375475/3032203/b9ecac92-e054-11e3-8a29-4d25d658ab6f.png)

I get this:

![screen shot 2014-05-20 at 21 27 10](https://cloud.githubusercontent.com/assets/1375475/3032198/afbfe19e-e054-11e3-951e-7243c0103043.png)

**Comment by infograf768** [comment]
I confirm. This is weird as the session check is similar to other comp in J

**Comment by aDaneInSpain** [comment]
I will look into this one. #jab14

**Comment by aDaneInSpain** [comment]
It is not default behaviour to delete an item by clicking a button in a list. Instead there should be a checkbox that allows selection list with a menu delete button. It is not possible to send a token id via a link so either way it should be a form submission if we want to maintain token security. Advise?

**Comment by mbabker** [comment]
My personal suggestion is to standardize the behavior as you would see across other CMS components, so I would remove this link.  If it's desired to keep it, you'd need it to trigger a form submission like the toolbar buttons do in order to keep the token security.

**Comment by aDaneInSpain** [comment]
I agree, and have started working on that Yesterday

**Comment by aDaneInSpain** [comment]
Maybe @infograf768 should implement this instead as it is kind of similar to the purge code in this https://github.com/joomla-projects/com_localise/pull/95 and I don't have much free time the next few days.

**Comment by infograf768** [comment]
The purge code has nothing to do with this. It does not delete existing xml files. It just deletes the localise table which has for result to reconstruct it the first time we get to any com_localise view after that purge.
