### ISSUE TITLE
Localise crashes when reading a wrong date

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#45]
Com_localise reads the date of the packages:

![screen shot 2014-05-30 at 12 28 52](https://cloud.githubusercontent.com/assets/1375475/3129608/a9c8b240-e7e6-11e3-89e4-4bf8dd68199f.png)

The problem is that when the date in the XML is not in american format it causes a crash in com_localise. To reproduce try to modify the creation date in the .XML manifest file of a language package and then make com_localise to read it. We need to make com_localise able to read a wrong date without chrashing. Later on the user can fix the date using this screen:

![screen shot 2014-05-30 at 12 44 36](https://cloud.githubusercontent.com/assets/1375475/3129643/4cb3bc70-e7e7-11e3-934b-c7312f18dc3f.png)

**Comment by javigomez** [comment]
Please check the bug at the minute 3m15s of the video (ask Javier for the link to the video)

**Comment by infograf768** [comment]
I have corrected the installation xml files since (Polish had a utf8 month in it).
Agree we need a solution. We could simply never use the calendar for that field.

**Comment by aDaneInSpain** [comment]
I forgot to close this issue in the pull request, so please close this @javigomez
