### ISSUE TITLE
Refactor the place where SQL files are

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#56]
Right now the folder structure for the SQL files is not good, please refactor the component so it follows the standard folder structure:

/ component / admin / sql / install / mysql / 
and
/ component / admin / sql / updates / mysql / 

remember to update the XML manifest ^_^

**Comment by gunjanpatel** [comment]
@javigomez Ready to test in https://github.com/joomla-projects/com_localise/pull/201
