### ISSUE TITLE
Fix columns in translations view

### ISSUE THREAD

**Issue by carcam** [joomla-projects/com_localise#70]
In translations view (administrator/index.php?option=com_localise&view=translations) replace current columns and icons with this structure:

Tag | Translation name | Translated | Storage / Path | Strings / Phrases | Author | Type | info

Tag: Language tag
Translated: Percentage of wokr done
Storage/Path: Path of the language file
Strings /Phrases: Number of strings language files contains
Author : Whose the author of the lnaguage file and it would be nice to include an icon if it's Joomla core
Type: Component, module, plugin, library...
Info: An icon with tooltip for extra information

**Comment by infograf768** [comment]
The info is presented first. I think we now have quite a good display.
Adding the path as a sub to the view. See PR
