### ISSUE TITLE
Add color legend to screens

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#71]
at 14m50s in the video we see the languages list and also the translation list, they have a colour for every status: 

green => translated, 
orange => translated but warning because the origin and translated are the same
red => is not tranlsated or is wrong

I suggest that we create a legend at the top of the screen that describes what the color does

**Comment by infograf768** [comment]
We do have this in the Translation view
![screen shot 2014-06-13 at 11 31 35](https://cloud.githubusercontent.com/assets/869724/3268482/95ac2ede-f2dd-11e3-864c-bc86df4503b1.png)

**Comment by javigomez** [comment]
ok, closing. Thanks.

Probably if we do a review of the UX with @babsgosgens we can probably find a more clear place, because the legend slider is not easy to find, at least I have not seen any user at JAB that discover it by themselves utils we mention that is there.

**Comment by babsgosgens** [comment]
Haven't found time yet, but will try next week.
