### ISSUE TITLE
Created packages doesn't work

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/com_localise#96]
related to #94 

If you generate the package you will get this:

![screen shot 2014-06-05 at 18 13 20](https://cloud.githubusercontent.com/assets/1375475/3190226/43afc3be-eccc-11e3-859c-2e4ed43dd232.png)

It generates a language.localise.php empty file

Also the XML is empty: 
![screen shot 2014-06-05 at 18 15 26](https://cloud.githubusercontent.com/assets/1375475/3190255/7fa26cbe-eccc-11e3-8cf6-ddca0c6619cd.png)

**Comment by infograf768** [comment]
@Javier
I guess you were mistaking in your test.
It does not work completely (see my comment in https://github.com/joomla-projects/com_localise/pull/94
But it does for the files we can choose in the field (here is a screnshot of part of the files)
![screen shot 2014-06-05 at 18 23 01](https://cloud.githubusercontent.com/assets/869724/3190375/c139db34-eccd-11e3-8eb0-19a63f626fc8.png)

**Comment by javigomez** [comment]
Adding some important comments to take into account when creating the Package feature:

One idea suggested was that you should be able to create Joomla language packages for:
- Site,
- Admin
- and Site & Admin togethere.

The reason is that there is some tranlsations of Joomla that are only done for frontend. However @infograf768  suggest that we don't do Site or Admin individual packages but always Full packages: 

[05/06/14 18:48:34] infograf768: we need always a full pack, even if some files are not included in admin
[05/06/14 18:48:54] infograf768: because of the way we Update or propose languages to install in J
[05/06/14 18:49:40] infograf768: the automatic cron needs that specific name for the zip as well as the version
[05/06/14 18:50:04] infograf768: fr-FR_joomla_lang_full_3.3.1v1.zip
[05/06/14 18:50:25] infograf768: is what I now get with com_localise as is in develop branch
[05/06/14 18:50:42] infograf768: but I need 3.3.1.1 as version in the xml

cc: @hikashop-nicolas

**Comment by infograf768** [comment]
For core, indeed. All core translations for Joomla HAVE to include some admin translated files as explained here: http://docs.joomla.org/J3.x:Making_a_Language_Pack_for_Joomla#The_Site-only_pack

**Comment by infograf768** [comment]
Also: since we have implemented the format for core files with its manifest, we prevent Uninstalling languages per se (as site or admin), only full packs can be Uninstalled, as this was creating issues.

**Comment by infograf768** [comment]
Please find here https://github.com/joomla-projects/com_localise/pull/103 a temporary solution that lets create a fully usable core pack (if the xx-XX.localise.php is present)
